<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DO1H4EQ" failures="1" tests="1" name="CompleteLogin" time="19.723" errors="0" timestamp="2023-03-13T20:14:01 IST">
  <testcase classname="UiScripts.TestCases.CompleteLogin" name="loginTest" time="2.914">
    <failure type="java.lang.AssertionError" message="User is not logged on succesfully expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User is not logged on succesfully expected [true] but found [false]
at UiScripts.TestCases.CompleteLogin.loginTest(CompleteLogin.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- CompleteLogin -->
